apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-configmap
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  # cara kedua - dinamis
  {{ toYaml .Values.config | nindent 2 }}