apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels: {{-  include "backend.labels" . | nindent 4 }}
data:
  DATABASE_PASSWORD: {{ .Values.secret.DATABASE_PASSWORD | b64enc }}
