apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cobain-sosmed.fullname" . }}-configmap
  labels:
    {{- include "cobain-sosmed.labels" . | nindent 4 }}
data:
  {{ toYaml .Values.config | nindent 2 }}
