apiVersion: v1
kind: Secret 
metadata:
  name: {{ include "cobain-sosmed.fullname" . }}-secret
  labels:
    {{- include "cobain-sosmed.labels" . | nindent 4 }}
data:
  DB_PASSWORD: {{.Values.secret.DB_PASSWORD | b64enc  }}
