apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend.fullname" . }}-secret
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  REACT_APP_BACKEND_URL: {{ .Values.secret.BACKEND_URL|b64enc}}